/**
 * Derive the effective Prisma schema for whatever DATABASE_URL points at.
 *
 * The project runs MySQL in development and Postgres in production, and Prisma
 * fixes the provider at the schema. Maintaining two schemas by hand is exactly
 * the drift this project exists to argue against — so `schema.prisma` is
 * canonical and this writes `schema.generated.prisma` with the one line that
 * differs swapped.
 *
 * The provider is inferred from the connection string, so nothing has to be
 * kept in sync by a human: point DATABASE_URL at MySQL and the next generate
 * produces a MySQL client.
 *
 * Run by `pnpm generate`, which every dev/build/typecheck script calls.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PRISMA_DIR = join(HERE, "..", "prisma");

const CANONICAL = join(PRISMA_DIR, "schema.prisma");
const DERIVED = join(PRISMA_DIR, "schema.generated.prisma");

/** postgres | postgresql | mysql | mariadb → a Prisma provider. */
export function providerFor(url) {
  if (!url) return "postgresql";
  const scheme = url.split(":")[0]?.toLowerCase();
  if (scheme === "mysql" || scheme === "mariadb") return "mysql";
  if (scheme === "postgres" || scheme === "postgresql") return "postgresql";
  if (scheme === "file") return "sqlite";
  return "postgresql";
}

// Neither node nor Prisma 7 loads .env implicitly. Node can do it without a
// dependency; a missing file is fine, since on Vercel the variable is injected
// into the environment directly.
try {
  process.loadEnvFile(join(HERE, "..", ".env"));
} catch {
  /* no .env — DATABASE_URL comes from the environment, or the default applies */
}

const provider = providerFor(process.env.DATABASE_URL);

const canonical = readFileSync(CANONICAL, "utf8").replace(/\r\n/g, "\n");

// Swap only the provider line inside the datasource block. Everything else —
// models, native types, indexes — is written once and shared.
const derived = canonical.replace(
  /(datasource\s+db\s*\{[^}]*?provider\s*=\s*)"[^"]+"/,
  `$1"${provider}"`,
);

if (derived === canonical && provider !== "postgresql") {
  console.error("prisma-schema: could not rewrite the datasource provider — check schema.prisma");
  process.exit(1);
}

writeFileSync(
  DERIVED,
  `// GENERATED by scripts/prisma-schema.mjs — do not edit.\n` +
    `// Source: prisma/schema.prisma · provider inferred from DATABASE_URL.\n\n` +
    derived,
  "utf8",
);

console.log(`prisma: schema.generated.prisma written for ${provider}`);
